#version: '3.8'
#obsolete as well as name docker-compose.yml -- use compose.yml instead
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8089:80"
    depends_on:
      - db

  api:
    build:
      context: ./nosql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9080:9080"
    env_file:
      - .env
    environment:
      ENVIRONMENT: DOCKER

  ana_report:
    build:
      context: ./ana_report
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
  dbeaver_data: