# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: localhost:32000/nosql_api:latest
        env:
        - name: ENVIRONMENT
          value: "DOCKER"
        - name: POSTGRES_HOST
          value: "postgres"  # Use the service name, not the IP
        - name: POSTGRES_PORT
          value: "5432"  # Use the port number, not a URL
        - name: POSTGRES_USER
          value: "myuser"  # Replace with your actual user
        - name: POSTGRES_PASSWORD
          value: "mypassword"  # Replace with your actual password
        - name: POSTGRES_DB
          value: "mydatabase"  # Replace with your act
        ports:
        - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  ports:
  - port: 9080
  selector:
    app: api