apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}-nosql-ana-report-service
  labels:
  {{- include "my-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.anaReportService.type }}
  selector:
    app: nosql-ana-report
    {{- include "my-helm.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.anaReportService.ports | toYaml | nindent 2 }}
