apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}-nosql-ana-report
  labels:
  {{- include "my-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.anaReport.type | default "ClusterIP" }}
  selector:
    app: nosql-ana-report
    {{- include "my-helm.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.anaReport.ports | default (list (dict "name" "http" "port" 8001 "targetPort" 8001)) | toYaml | nindent 2 }}
