apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}-pgadmin
  labels:
    {{- include "my-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgadmin.service.type | default "ClusterIP" }}
  selector:
    app: pgadmin
    {{- include "my-helm.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.pgadmin.service.ports | default (list (dict "name" "http" "port" 80 "targetPort" 80)) | toYaml | nindent 4 }}