apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-helm.fullname" . }}-postgres-pv
  labels:
  {{- include "my-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/docker/volumes/nosql_postgres_data/_data
  storageClassName: ""
