apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}-postgres
  labels:
  {{- include "my-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type | default "ClusterIP" }}
  selector:
    app: postgres
    {{- include "my-helm.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.postgresql.service.port | default 5432 }}
      targetPort: {{ .Values.postgresql.service.port | default 5432 }}
      protocol: TCP