# Global settings
kubernetesClusterDomain: cluster.local

# Global service configuration (fallback)
service:
  port: 80  # Default port if not explicitly defined for a service

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository:  localhost:32000/postgres
    tag: latest
  replicaCount: 1
  env:
    POSTGRES_DB: mydatabase
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword
  service:
    type: ClusterIP  # Add the missing 'type' field
    port: 5432
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

# pgAdmin configuration
pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
  replicaCount: 1
  env:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: admin
  service:
    type: ClusterIP
    port: 80

# API service configuration
api:
  enabled: true
  image:
    repository: localhost:32000/nosql_api
    tag: latest
  replicaCount: 1
  env:
    ENVIRONMENT: "DOCKER"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"
    POSTGRES_DB: "mydatabase"
  service:
    type: ClusterIP
    port: 9080

# Ana Report service configuration
anaReport:
#nosqlAnaReport:
  type: ClusterIP
  enabled: true
  image:    
    repository: 192.168.0.103:32000/nosql_ana_report
    tag: latest
  replicaCount: 1
  env:
    ENVIRONMENT: "DOCKER"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"
    POSTGRES_DB: "mydatabase"
  service:
    type: ClusterIP
    port: 8001
    targetPort: 8001
# ServiceAccount configuration


anaReportService:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# HPA horizontal pod autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true  # Set to true if you need a ServiceAccount

pvc:
  postgresPvc:
    storageRequest: 1Gi
    storageClass: ""
